# Welcome to Plus!
#
# This config file affects your whole blog.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
title:                  WhiteWater Oy animaatiostudio
description:            Visuaalista sisällöntuotantoa animaation keinoin.
url:                    "" # Site base hostname & protocol, e.g. http://example.com
baseurl:                # Site subpath, e.g. /blog
lang:                   fin
logo:                   whitewater_logo.png
logo_light:             whitewater_logo_light.png
permalink:              /:title/ # Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
date_format:            "%b %-d, %Y" # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
uploads:                /uploads/ # Path to post content assets directory i.e post images, pdfs etc
template:               base

paginate:               6 # Number of posts displayed on blog page
paginate_path:          "/blog/:num/" # Blog path

# Default author settings
author:
  name:                 Ville Heikkilä
  avatar:               avatar-ville.png
  title:                Visual designer/Graphic production
  bio:                  Olen visuaalinen suunnittelija ja liikkuvan kuvan ammattilainen. Erityisosaamistani ovat 3D-grafiikka ja animaatio sekä moninaisten visuaalisten toteutusten hallinta.
  url:
  email:                ville@whitewater.fi
  website:
  facebook:             https://www.facebook.com/WhitewaterOy/
  flickr:
  dribbble:
  github:
  googleplus:
  instagram:            https://www.instagram.com/WhitewaterOy
  linkedin:
  pinterest:
  twitter:
  vimeo:
  youtube:

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
  john:
    name:               Ville Heikkilä
    title:              Visual designer/Graphic production, ville@whitewater.fi, 044 5347381
    email:              ville@whitewater.fi
    avatar:             avatar-ville.png
  evan:
    name:               Evan Wells
    title:              Support
    avatar:             avatar-evan.png
  sara:
    name:               Sara Galen
    title:              Lead Developer
    avatar:             avatar-sara.png
  alex:
    title:              Design Engineer
    name:               Alex Koch
    avatar:             avatar-alex.png
  daniel:
    title:              Developer
    name:               Daniel Shultz
    avatar:             avatar-daniel.png
  tom:
    title:              Developer
    name:               Tom Farrell
    avatar:             avatar-tom.png

navbar:
  layout:               default # default, center
  color:                dark # text color, dark or light
  animation:            true
  sticky:               true
  search:               false

footer:                 # Default footer image settings
  style:                default # default, muted, primary, secondary
  layout:               center # center or columns
  copyright:            WhiteWater Oy 2020

mailchimp:
  form_action:          000000
  hidden_name:          000000

google_analytics:       # Google analytics code, get your code here https://www.google.com/analytics/
google_maps_api_key: AIzaSyB3CinAQOI9CDamoruW_XBuVuU69j4JWU4

disqus:
  shortname:            # Disqus comments shortname, requires Disqus account https://disqus.com/

instagram_accesstoken:

donations:
  paypal:
    id:                 # PayPal button ID
    navbar:             # true

# Social share buttons
social_share:
  twitter:              false
  facebook:             false
  linkedin:             false
  pinterest:            false
  reddit:               false

# Social buttons
social_networks:
  email:                ville@whitewater.fi
  website: whitewater.fi
  facebook:             https://www.facebook.com/whitewateroy
  flickr:
  dribbble:
  github:
  googleplus:
  instagram:            https://www.instagram.com/whitewateroy
  linkedin:
  pinterest:
  twitter:
  vimeo:
  youtube:             https://www.youtube.com/channel/UCQenIezo52aRbO68jr3TH6A

# Build settings
markdown:               kramdown
highlighter:            rouge
kramdown:
  toc_levels:           "2"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

exclude:
  - vendor
  - .bundle
  - .sass-cache
  - config
  - Gemfile
  - Gemfile.lock
  - node_modules
  - log
  - tmp
  - Rakefile
  - package.json
  - CHANGELOG
  - LICENSE
  - README
  - /docs

sass:
  style:                compressed

# collections:
collections:
  blocks:
    output:             false
  sidebars:
    output:             false
  faqs:
    output:             false
  portfolio:
    output:             true

# Defaults
defaults:
  # _posts
  - scope:
      path:                 ""
      type:                 posts
    values:
      layout:               post
      section:              large
      sidebar:
        right:              blog
      comments:             # true
      share:                true
      related:              true
      mailchimp:            true
      navbar:
        transparent:        true
        transparent_color:  light
      header:
        layout:             center
        background_overlay: "rgba(0, 0, 0, 0.5)"
        color:              light
        header_size:        large
        heading_size:       medium
        parallax:           true
  # _pages
  - scope:
      path:                 ""
      type:                 pages
    values:
      layout:               page
  # _portfolio
  - scope:
      path:                 ""
      type:                 portfolio
    values:
      layout:               page
